# Generated by Django 5.0.3 on 2024-03-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='shift_hours',
            field=models.FloatField(default=8, verbose_name='Shift hours'),
        ),
    ]
