# Generated by Django 5.0.3 on 2024-03-27 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attendance_shift_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factory',
            name='shift_hours',
            field=models.PositiveIntegerField(default=8, validators=[django.core.validators.MaxValueValidator(24)], verbose_name='Shift hours'),
        ),
    ]
