# Generated by Django 4.2.6 on 2023-12-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_section_factory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='performer',
            field=models.BooleanField(default=False, verbose_name='Performer'),
        ),
    ]
