# Generated by Django 4.2.6 on 2023-12-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_performer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='performer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_performer',
            field=models.BooleanField(default=False, verbose_name='Is performer'),
        ),
    ]
