# Generated by Django 4.2.6 on 2024-02-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_user_performer_user_is_performer'),
    ]

    operations = [
        migrations.AddField(
            model_name='factory',
            name='file',
            field=models.FileField(blank=True, upload_to='files/', verbose_name='File'),
        ),
    ]
