# Generated by Django 4.2.6 on 2024-02-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_factory_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('uz-CR', 'Uzbek'), ('uz', 'Uzbek')], default='ru', max_length=5),
        ),
    ]
