# Generated by Django 5.0.3 on 2024-09-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_factory_shift_hours'),
        ('accounts', '0009_alter_user_preferred_language'),
    ]

    operations = [
    ]
