# Generated by Django 4.2.6 on 2024-03-22 05:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('repair_records', '0001_initial'),
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeatedTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_time', models.TimeField(null=True, verbose_name='Allocated Time')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly'), ('Y', 'Yearly')], max_length=1, verbose_name='Frequency')),
                ('interval', models.PositiveIntegerField(verbose_name='Interval')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repair_records.equipment', verbose_name='Equipment')),
                ('equipment_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair_records.equipmentnode', verbose_name='Node')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.factory', verbose_name='Factory')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_master', related_query_name='master', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
                ('performers', models.ManyToManyField(related_name='%(app_label)s_%(class)s_performers', related_query_name='performers', to=settings.AUTH_USER_MODEL, verbose_name='Performers')),
                ('repair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repair_records.repairtype', verbose_name='Repair Type')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section', verbose_name='Section')),
                ('work_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair_records.workaction', verbose_name='Work Action')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair_records.worktype', verbose_name='Work Type')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='ScheduledTask',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_time', models.TimeField(null=True, verbose_name='Allocated Time')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('is_summarized', models.BooleanField(default=False)),
                ('scheduled_date', models.DateTimeField(null=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repair_records.equipment', verbose_name='Equipment')),
                ('equipment_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair_records.equipmentnode', verbose_name='Node')),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.factory', verbose_name='Factory')),
                ('master', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_master', related_query_name='master', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
                ('performers', models.ManyToManyField(related_name='%(app_label)s_%(class)s_performers', related_query_name='performers', to=settings.AUTH_USER_MODEL, verbose_name='Performers')),
                ('repair_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repair_records.repairtype', verbose_name='Repair Type')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.section', verbose_name='Section')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.repeatedtask')),
                ('work_action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair_records.workaction', verbose_name='Work Action')),
                ('work_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='repair_records.worktype', verbose_name='Work Type')),
            ],
            options={
                'verbose_name': 'Scheduled Task',
                'verbose_name_plural': 'Scheduled Tasks',
            },
        ),
    ]
