# Generated by Django 5.0.3 on 2024-04-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeatedtask',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
        migrations.AddField(
            model_name='scheduledtask',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
